info:
    app:
      name: catalog-statistic-service
      description: Statistics
    build:
        artifact: ${project.artifactId}
        name: ${project.name}
        description: ${project.description}
        version: ${project.version}

server:
    port: 8022
    
zipkin:
    collector-hostname: localhost
    
monitoring:
    hostname: localhost
    port: 2003
    period: 1